# Generated by Django 5.2.1 on 2025-05-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_generalrequirement_studentrequirement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentRequirement',
        ),
    ]
